[package]
name = "youtube-comment-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
google-youtube3 = "7.0.0"
hyper = "1.8.1"
hyper-rustls = "0.27.7"
tokio = { version = "1.49.0", features = ["full"] }
yup-oauth2 = "12.1.2"
